### ISSUE TITLE
Problem with (typically non-option) argument whose name clashes with a metatable-provided member

### ISSUE THREAD

**Issue by rrthomas** [gvvaughan/optparse#5]
Using the example code you supply, via `stdlib`, so I've changed just the `require` to `require "stdlib.optparse"` and with Lua 5.4 (though it shouldn't matter which version):

```
lua foo.lua clone
lua: /home/rrt/.local/share/lua/5.4/std/optparse.lua:518: attempt to index a function value (field '?')
stack traceback:
	/home/rrt/.local/share/lua/5.4/std/optparse.lua:518: in method 'parse'
	foo.lua:35: in main chunk
	[C]: in ?
```

I guess `clone` is being found by the metatable, as it's not listed as a key if I simply print out all the keys in `self` at that point.

**Comment by rrthomas** [comment]
I found this bug via my command-line colorizing wrapper, `cw`, when I tried to run:

```
env git clone …
```

**Comment by gvvaughan** [comment]
Hi Rueben! Thanks for the bug report.

Does this bug reproduce in this stamdalone optparse? I divorced it from stdlib a few years ago in my ongoing project for using many small modules, and think you might be using an old version from the all-in-one-stdlib...

**Comment by rrthomas** [comment]
I'm using an old version from all-in-one stdlib, but it is the latest stdlib release (41.2.2)…should I refile the bug report there? I'd be very happy of course to update my dependencies, and I guess I could simply use optparse directly rather than via stdlib as a workaround?

**Comment by gvvaughan** [comment]
Hi Reuben,

Please do try the standalone release of optparse as a workaround, and let me know if the bug is still there.

I think I actually have all the parts in place now to make a stdlib-42 which will be a shim that pulls in all the submodules (including gvvaughan/optparse) plus any necessary backwards compatibility hacks... and start to encourage users to add only the submodules they actually need and use to their projects rather than pulling in the whole kaboodle.  But, I need to find time to check that is really true and check that the shim release still passes all the tests in the current release correctly before I push.  In any case, moving from mega-stdlib to individual std.foo modules is arguably the cleanest way forward for cw at this point?

Cheers,
Gary

**Comment by rrthomas** [comment]
It works fine; I didn't remove the workaround I put in (which was in any case also a bug-fix for `cw`) to see whether the problem I had repeated. Closing.
